name: fibrosis

channels:
  - defaults
  - conda-forge
  
dependencies:
  - python==3.6.7
  - pip==20.2.2
  - numpy==1.17.2 
  - pandas==1.1.1
  - scikit-learn==0.21.3
  - pydicom==2.0.0
  - scipy==1.4.1
  - matplotlib==3.2.1
  - seaborn==0.9.0
  - Pillow==7.1.2
  - tqdm==4.46.0
  - pickleshare==0.7.5
  - Keras==2.4.3
  - pip:
    - opencv-python==4.4.0.44
    - tensorflow-addons==0.11.2
    - tensorflow==2.2.0
    - streamlit==0.60.0
    - efficientnet==1.1.1




